/**
 * English-only string dictionary for the MVP.
 *
 * Reserved top-level domains `common`, `error`, and `validation` are always
 * present. Every other top-level domain MUST correspond to a capability folder
 * under `openspec/specs/<capability>/`. See `./README.md` and the `platform`
 * capability spec for the full contract.
 */
export const en = {
  common: {
    app: {
      name: "NomadHome",
      tagline: "Co-living and workspaces for digital nomads",
    },
    action: {
      close: "Close",
      submit: "Submit",
      cancel: "Cancel",
      save: "Save",
    },
    loading: "Loading…",
    submitting: "…",
  },
  nav: {
    login: "Log in",
    logout: "Log out",
    register: "Sign up",
    my_bookings: "My Bookings",
    host_dashboard: "Host Dashboard",
    become_host: "Become a host",
    admin: "Admin",
    admin_users: "Users",
    admin_listings: "Listings",
  },
  auth: {
    login: {
      title: "Welcome back",
      subtitle: "Sign in to your NomadHome account",
      email_label: "Email",
      password_label: "Password",
      submit: "Log in",
      no_account: "Don't have an account?",
      sign_up_link: "Sign up",
      error: "Invalid email or password.",
    },
    register: {
      title: "Create your account",
      subtitle: "Start finding co-living spaces and workspaces",
      email_label: "Email",
      password_label: "Password",
      confirm_password_label: "Confirm password",
      passwords_mismatch: "Passwords do not match.",
      submit: "Create account",
      have_account: "Already have an account?",
      login_link: "Log in",
      error: "Registration failed. Please try again.",
    },
    forbidden: {
      title: "Access denied",
      message: "You don't have permission to view this page.",
    },
  },
  error: {
    generic: {
      unexpected: "Something went wrong. Please try again.",
    },
    not_found: {
      title: "404 — Page not found",
      home: "Go home",
    },
    title: "Something went wrong",
    unexpected: "An unexpected error occurred. Please try again.",
    go_back: "Go back",
    go_home: "Go to home",
  },
  validation: {
    required: {
      field: "This field is required.",
    },
    email: {
      invalid: "Enter a valid email address.",
    },
    password: {
      too_short: "Password must be at least 10 characters.",
      needs_letter: "Password must include at least one letter.",
      needs_digit: "Password must include at least one number.",
    },
  },
  identity: {
    register: {
      failed: "We couldn't complete your registration. Please try again.",
    },
    login: {
      invalid_credentials: "Invalid email or password.",
    },
    become_host: {
      title: "Become a host",
      subtitle: "Set up your host profile to start listing properties and workspaces.",
      display_name_label: "Display name",
      payout_email_label: "Payout email",
      terms_label: "I accept the host terms and conditions",
      submit: "Become a host",
      terms_required: "You must accept the host terms to continue.",
      already_host: "You're already set up as a host.",
      email_not_verified: "Please verify your email address before becoming a host.",
    },
    verify_email: {
      pending: "Verifying your email…",
      success_title: "Email verified!",
      success_body: "Your account is confirmed. You can now log in.",
      success_cta: "Log in",
      error_title: "Link invalid or expired",
      error_body:
        "This verification link has already been used or has expired. Please register again.",
      error_cta: "Register",
    },
  },
  listings: {
    create: {
      invalid_type: "Choose either a property or a workspace.",
      invalid_country: "Enter a valid country code.",
      invalid_capacity: "Capacity must be at least 1.",
      invalid_rate: "Nightly rate must be greater than 0.",
      amenities_required: "Select at least one amenity.",
      unknown_amenity: "One or more selected amenities don't exist.",
    },
    photo: {
      invalid_position: "Position must be a non-negative integer.",
      not_found: "Photo not found.",
      position_conflict: "A photo already exists at that position.",
      forbidden: "You can only manage photos on your own listings.",
    },
    publish: {
      no_photo: "Add at least one photo before publishing.",
    },
    availability: {
      invalid_date: "Date must be in YYYY-MM-DD format.",
      end_before_start: "End date must be after start date.",
      not_found: "Availability block not found.",
      forbidden: "You can only manage availability on your own listings.",
      overlap: "This date range overlaps an existing block.",
    },
    error: {
      not_found: "Listing not found.",
      forbidden: "You can only manage your own listings.",
    },
    detail: {
      amenities: "Amenities",
      reviews: "Reviews",
      no_reviews: "No reviews yet.",
      rating: "Rating",
      book_now: "Book now",
      login_to_book: "Log in to book",
      capacity: "Capacity",
      not_found: "Listing not found.",
      guests: "guests",
    },
  },
  search: {
    error: {
      end_before_start: "Check-out must be after check-in.",
      invalid_dates: "Invalid date format. Use YYYY-MM-DD.",
      invalid_page: "Page must be an integer greater than or equal to 1.",
      invalid_page_size: "Page size must be an integer between 1 and 100.",
    },
    page_title: "Find your next stay",
    city_label: "City",
    city_placeholder: "e.g. Lisbon",
    checkin_label: "Check-in",
    checkout_label: "Check-out",
    submit: "Search",
    no_results: "No listings found for your search.",
    nightly_rate: "/ night",
    per_night: "per night",
    filter_title: "Filters",
    filter_type_label: "Type",
    filter_type_all: "All types",
    filter_type_property: "Property",
    filter_type_workspace: "Workspace",
    filter_amenities_label: "Amenities",
    filter_min_price_label: "Min price ($/night)",
    filter_max_price_label: "Max price ($/night)",
    filter_capacity_label: "Min guests",
    filter_reset: "Reset filters",
    filter_any: "Any",
    filter_amenity_wifi: "Wi-Fi",
    filter_amenity_parking: "Parking",
    filter_amenity_pool: "Pool",
    filter_amenity_gym: "Gym",
    filter_amenity_kitchen: "Kitchen",
    filter_amenity_ac: "A/C",
  },
  booking: {
    error: {
      not_found: "Booking not found.",
      listing_not_found: "Listing not found or not available for booking.",
      self_booking: "You cannot book your own listing.",
      overlap: "These dates are no longer available.",
      not_cancellable: "This booking cannot be cancelled.",
      checkin_passed: "Check-in date has already passed.",
      no_fee_config: "Platform fee configuration is missing. Contact support.",
      email_not_verified: "Please verify your email address before booking.",
    },
    ui: {
      form_title: "Confirm your booking",
      checkin_label: "Check-in",
      checkout_label: "Check-out",
      nights: "nights",
      night: "night",
      nightly_rate: "per night",
      total: "Total",
      pay_now: "Pay now",
      select_dates: "Select check-in and check-out dates to book.",
      back_to_listing: "Back to listing",
      success_title: "Booking confirmed!",
      success_message: "Your booking is confirmed. You will receive a confirmation email shortly.",
      view_bookings: "View my bookings",
      cancel_title: "Payment cancelled",
      cancel_message: "Your payment was not completed. No charges were made.",
      back_to_search: "Back to search",
      processing: "Processing your payment…",
    },
    dashboard: {
      title: "My Bookings",
      no_bookings: "You have no bookings yet.",
      status_pending: "Pending Payment",
      status_confirmed: "Confirmed",
      status_cancelled: "Cancelled",
      status_completed: "Completed",
      complete_payment_button: "Complete payment",
      cancel_button: "Cancel",
      cancel_modal_title: "Cancel booking",
      cancel_modal_body: "Are you sure you want to cancel this booking?",
      cancel_reason_label: "Reason (optional)",
      cancel_reason_placeholder: "Tell us why you're cancelling...",
      cancel_confirm: "Yes, cancel",
      cancel_error_passed: "Check-in date has already passed.",
      cancel_error_generic: "This booking cannot be cancelled.",
      review_button: "Leave a review",
      review_modal_title: "How was your stay?",
      review_rating_label: "Rating",
      review_text_label: "Your review (optional)",
      review_text_placeholder: "Share your experience...",
      review_submit: "Submit review",
      review_success: "Review submitted!",
      review_already_exists: "You've already reviewed this booking.",
      nights: "nights",
      night: "night",
    },
  },
  payments: {
    error: {
      booking_not_pending: "Payment can only be initiated for a pending booking.",
      booking_not_found: "Booking not found.",
      stripe_key_missing: "Stripe is not configured.",
      webhook_invalid_signature: "Invalid webhook signature.",
      double_payout: "One or more bookings are already settled.",
    },
  },
  reviews: {
    error: {
      booking_not_found: "Booking not found.",
      booking_not_confirmed: "Only confirmed bookings can be reviewed.",
      checkout_not_passed: "Reviews can only be submitted after check-out.",
      already_exists: "You have already reviewed this booking.",
    },
  },
  host: {
    listings: {
      title: "My Listings",
      new_listing: "New listing",
      edit: "Edit",
      no_listings: "You have no listings yet.",
      status_draft: "Draft",
      status_published: "Published",
      status_disabled: "Disabled",
      publish: "Publish",
      unpublish: "Unpublish",
      save: "Save changes",
      create_title: "Create a new listing",
      edit_title: "Edit listing",
      field_title: "Title",
      field_description: "Description",
      field_type: "Type",
      field_city: "City",
      field_country: "Country (2-letter code)",
      field_address: "Address",
      field_capacity: "Capacity (guests)",
      field_rate: "Nightly rate",
      field_currency: "Currency",
      field_amenities: "Amenities",
      type_property: "Property",
      type_workspace: "Workspace",
      country_placeholder: "Select a country…",
      creating: "Creating…",
      hint_title: "Give your space a clear, catchy name (min 5 characters).",
      hint_description:
        "Describe amenities, vibe, and what makes your space unique (min 20 characters).",
      hint_type: "Property = a place to sleep and live. Workspace = a desk or office.",
      hint_city: "The city where guests will stay (e.g. Madrid, Lisbon).",
      hint_country: "Select the country where your listing is located.",
      hint_address: "Street name and number (e.g. Calle del Pez 12, Malasaña).",
      hint_capacity: "Maximum number of guests the space can accommodate.",
      hint_rate: "Price per night in the selected currency (e.g. 75 for €75.00).",
      hint_currency: "Select the currency you want to charge guests in.",
      hint_amenities: "Select all that apply — guests can filter by these.",
      confirmed_booking_singular: "confirmed booking",
      confirmed_booking_plural: "confirmed bookings",
      amenity_wifi: "Wi-Fi",
      amenity_kitchen: "Kitchen",
      amenity_workspace_desk: "Dedicated desk",
      amenity_meeting_room: "Meeting room",
      amenity_phone_booth: "Phone booth",
      amenity_laundry: "Laundry",
      amenity_air_conditioning: "Air conditioning",
      amenity_heating: "Heating",
      amenity_parking: "Parking",
      amenity_coffee: "Coffee",
    },
    photos: {
      title: "Photos",
      upload: "Upload photo",
      delete: "Delete",
      uploading: "Uploading...",
      no_photos: "No photos yet.",
    },
    availability: {
      title: "Blocked dates",
      start_label: "Start date",
      end_label: "End date",
      block: "Block dates",
      delete: "Remove",
      no_blocks: "No blocked dates.",
      overlap_error: "These dates overlap with an existing blocked period.",
    },
    upcoming: {
      title: "Upcoming bookings",
      no_bookings: "No upcoming bookings.",
      listing_col: "Listing",
      guest_col: "Guest",
      checkin_col: "Check-in",
      checkout_col: "Check-out",
    },
    bookings: {
      title: "All Bookings",
      no_bookings: "No bookings yet.",
      listing_col: "Listing",
      guest_col: "Guest",
      checkin_col: "Check-in",
      checkout_col: "Check-out",
      status_col: "Status",
      amount_col: "Amount",
    },
  },
  admin: {
    users: {
      title: "Users",
      email_col: "Email",
      roles_col: "Roles",
      status_col: "Status",
      actions_col: "Actions",
      active: "Active",
      disabled: "Disabled",
      disable: "Disable",
      enable: "Re-enable",
      no_users: "No users found.",
    },
    listings: {
      title: "Listings",
      title_col: "Title",
      type_col: "Type",
      city_col: "City",
      host_col: "Host",
      status_col: "Status",
      actions_col: "Actions",
      disable: "Disable",
      enable: "Re-enable",
      no_listings: "No listings found.",
    },
  },
  home: {
    hero: {
      eyebrow: "Co-living & workspaces · 9 cities",
      headline_pre: "Find a place to",
      headline_em: "land",
      headline_post: ", and people to land with.",
      subheadline:
        "Private rooms in beautiful shared homes, a desk waiting in every city, and a community that turns a stay into a circle of friends.",
      search_label: "Where",
      search_placeholder: "City or destination",
      search_aria: "Search",
      trust_rating: "4.9 from 1,200+ members",
      trust_nps: "NPS +62 · 92% would stay again",
    },
    featured: {
      eyebrow: "Featured · this month",
      headline_pre: "Houses we’d",
      headline_em: "recommend",
      headline_post: "right now.",
      see_all: "See all stays",
    },
    how_it_works: {
      eyebrow: "How it works",
      headline_pre: "Three steps to your",
      headline_em: "next home",
      step_01_heading: "Pick a city, pick your dates",
      step_01_body:
        "Browse designed homes across nine cities. Filter by coworking, length of stay, pets, or how close you want to be to the beach.",
      step_02_heading: "Book a room, get the keys",
      step_02_body:
        "One booking covers your private room and full workspace access. We handle the lease, the Wi-Fi, the kitchen — you just bring a bag.",
      step_03_heading: "Move in, meet the house",
      step_03_body:
        "Your host meets you at the door. By the first dinner you’ll know your neighbors — and you’ll keep running into them in other cities.",
    },
    coliving: {
      eyebrow: "Co-living",
      headline_pre: "A private room in a home that’s actually been",
      headline_em: "designed",
      body: "Not a hostel, not a sublet. Real bedrooms, stocked kitchens, communal tables built for long dinners — and housekeeping so you never argue about the dishes.",
      feature_1: "Private, furnished bedrooms — yours alone.",
      feature_2: "Weekly cleaning, fresh linens, and utilities included.",
      feature_3: "One transparent price per month — no deposits, no surprises.",
      price_label: "All included",
      price_value: "MX$ 18,500",
      price_period: "/ mo",
    },
    workspace: {
      eyebrow: "Workspace",
      headline_pre: "A desk waiting for you in",
      headline_em: "every",
      headline_post: "city.",
      body: "Your stay includes a seat at the local coworking space — fast Wi-Fi, quiet rooms, phone booths and an espresso bar. Book a desk for the day or a meeting room by the hour.",
      feature_1: "300 Mbps Wi-Fi, monitors, and ergonomic chairs.",
      feature_2: "Reserve desks & meeting rooms from the member app.",
      feature_3: "Access carries across the whole network as you travel.",
      status_open: "Open now",
      status_desks: "11 desks · 2 booths free",
    },
    locations: {
      eyebrow: "The network · 9 cities · 4 countries",
      headline_pre: "Stay in one. Belong to",
      headline_em: "all of them",
      explore_all: "Explore all",
    },
    stats: {
      cities_label: "cities, and counting",
      rooms_label: "private rooms",
      occupancy_label: "network occupancy",
      nps_label: "member NPS",
    },
    testimonial: {
      quote_original_1: "Llegué para tres semanas.",
      quote_original_2: "Me quedé tres meses.",
      quote_translation: "“I came for three weeks. I stayed three months.”",
      author_name: "Andrés Soto",
      author_bio: "Designer · stayed at Casa del Fig, Oaxaca",
    },
    cta: {
      eyebrow: "Your next home is one search away",
      headline_pre: "Pick a city. We’ll save",
      headline_em: "the rest",
      body: "Three rooms left in Oaxaca this month, and new houses opening in Cape Town and Buenos Aires this summer.",
    },
    footer: {
      tagline:
        "Co-living and workspaces for people who’d rather live in a few places than visit many.",
      copyright: "© 2026 NomadHome · Una red de casas y espacios de trabajo",
      privacy: "Privacy",
      terms: "Terms",
      cookies: "Cookies",
      nav_stay: "Stay",
      nav_company: "Company",
      nav_support: "Support",
      link_find_home: "Find a home",
      link_locations: "Locations",
      link_workspaces: "Workspaces",
      link_long_stays: "Long stays",
      link_about: "About us",
      link_become_host: "Become a host",
      link_community: "Community",
      link_careers: "Careers",
      link_help: "Help center",
      link_house_rules: "House rules",
      link_contact: "Contact",
    },
  },
} as const;

export type Dictionary = typeof en;
