/**
 * English-only string dictionary for the MVP.
 *
 * Reserved top-level domains `common`, `error`, and `validation` are always
 * present. Every other top-level domain MUST correspond to a capability folder
 * under `openspec/specs/<capability>/`. See `./README.md` and the `platform`
 * capability spec for the full contract.
 */
export const en = {
  common: {
    app: {
      name: "NomadHome",
      tagline: "Co-living and workspaces for digital nomads",
    },
    action: {
      close: "Close",
      submit: "Submit",
      cancel: "Cancel",
      save: "Save",
    },
  },
  nav: {
    login: "Log in",
    logout: "Log out",
    register: "Sign up",
    my_bookings: "My Bookings",
    host_dashboard: "Host Dashboard",
    become_host: "Become a host",
    admin: "Admin",
  },
  auth: {
    login: {
      title: "Welcome back",
      subtitle: "Sign in to your NomadHome account",
      email_label: "Email",
      password_label: "Password",
      submit: "Log in",
      no_account: "Don't have an account?",
      sign_up_link: "Sign up",
      error: "Invalid email or password.",
    },
    register: {
      title: "Create your account",
      subtitle: "Start finding co-living spaces and workspaces",
      email_label: "Email",
      password_label: "Password",
      confirm_password_label: "Confirm password",
      passwords_mismatch: "Passwords do not match.",
      submit: "Create account",
      have_account: "Already have an account?",
      login_link: "Log in",
      error: "Registration failed. Please try again.",
    },
    forbidden: {
      title: "Access denied",
      message: "You don't have permission to view this page.",
    },
  },
  error: {
    generic: {
      unexpected: "Something went wrong. Please try again.",
    },
  },
  validation: {
    required: {
      field: "This field is required.",
    },
    email: {
      invalid: "Enter a valid email address.",
    },
    password: {
      too_short: "Password must be at least 10 characters.",
      needs_letter: "Password must include at least one letter.",
      needs_digit: "Password must include at least one number.",
    },
  },
  identity: {
    register: {
      failed: "We couldn't complete your registration. Please try again.",
    },
    login: {
      invalid_credentials: "Invalid email or password.",
    },
    become_host: {
      title: "Become a host",
      subtitle: "Set up your host profile to start listing properties and workspaces.",
      display_name_label: "Display name",
      payout_email_label: "Payout email",
      terms_label: "I accept the host terms and conditions",
      submit: "Become a host",
      terms_required: "You must accept the host terms to continue.",
      already_host: "You're already set up as a host.",
    },
  },
  listings: {
    create: {
      invalid_type: "Choose either a property or a workspace.",
      invalid_country: "Enter a valid country code.",
      invalid_capacity: "Capacity must be at least 1.",
      invalid_rate: "Nightly rate must be greater than 0.",
      amenities_required: "Select at least one amenity.",
      unknown_amenity: "One or more selected amenities don't exist.",
    },
    photo: {
      invalid_position: "Position must be a non-negative integer.",
      not_found: "Photo not found.",
      position_conflict: "A photo already exists at that position.",
      forbidden: "You can only manage photos on your own listings.",
    },
    publish: {
      no_photo: "Add at least one photo before publishing.",
    },
    availability: {
      invalid_date: "Date must be in YYYY-MM-DD format.",
      end_before_start: "End date must be after start date.",
      not_found: "Availability block not found.",
      forbidden: "You can only manage availability on your own listings.",
      overlap: "This date range overlaps an existing block.",
    },
    error: {
      not_found: "Listing not found.",
      forbidden: "You can only manage your own listings.",
    },
    detail: {
      amenities: "Amenities",
      reviews: "Reviews",
      no_reviews: "No reviews yet.",
      rating: "Rating",
      book_now: "Book now",
      login_to_book: "Log in to book",
      capacity: "Capacity",
      not_found: "Listing not found.",
      guests: "guests",
    },
  },
  search: {
    error: {
      end_before_start: "Check-out must be after check-in.",
      invalid_dates: "Invalid date format. Use YYYY-MM-DD.",
      invalid_page: "Page must be an integer greater than or equal to 1.",
      invalid_page_size: "Page size must be an integer between 1 and 100.",
    },
    page_title: "Find your next stay",
    city_label: "City",
    city_placeholder: "e.g. Lisbon",
    checkin_label: "Check-in",
    checkout_label: "Check-out",
    submit: "Search",
    no_results: "No listings found for your search.",
    nightly_rate: "/ night",
    per_night: "per night",
    filter_title: "Filters",
    filter_type_label: "Type",
    filter_type_all: "All types",
    filter_type_property: "Property",
    filter_type_workspace: "Workspace",
    filter_amenities_label: "Amenities",
    filter_min_price_label: "Min price ($/night)",
    filter_max_price_label: "Max price ($/night)",
    filter_capacity_label: "Min guests",
    filter_reset: "Reset filters",
  },
  booking: {
    error: {
      not_found: "Booking not found.",
      listing_not_found: "Listing not found or not available for booking.",
      self_booking: "You cannot book your own listing.",
      overlap: "These dates are no longer available.",
      not_cancellable: "This booking cannot be cancelled.",
      checkin_passed: "Check-in date has already passed.",
      no_fee_config: "Platform fee configuration is missing. Contact support.",
    },
    ui: {
      form_title: "Confirm your booking",
      checkin_label: "Check-in",
      checkout_label: "Check-out",
      nights: "nights",
      night: "night",
      nightly_rate: "per night",
      total: "Total",
      pay_now: "Pay now",
      select_dates: "Select check-in and check-out dates to book.",
      back_to_listing: "Back to listing",
      success_title: "Booking confirmed!",
      success_message: "Your booking is confirmed. You will receive a confirmation email shortly.",
      view_bookings: "View my bookings",
      cancel_title: "Payment cancelled",
      cancel_message: "Your payment was not completed. No charges were made.",
      back_to_search: "Back to search",
    },
    dashboard: {
      title: "My Bookings",
      no_bookings: "You have no bookings yet.",
      status_pending: "Pending Payment",
      status_confirmed: "Confirmed",
      status_cancelled: "Cancelled",
      status_completed: "Completed",
      cancel_button: "Cancel",
      cancel_modal_title: "Cancel booking",
      cancel_modal_body: "Are you sure you want to cancel this booking?",
      cancel_reason_label: "Reason (optional)",
      cancel_reason_placeholder: "Tell us why you're cancelling...",
      cancel_confirm: "Yes, cancel",
      cancel_error_passed: "Check-in date has already passed.",
      cancel_error_generic: "This booking cannot be cancelled.",
      review_button: "Leave a review",
      review_modal_title: "How was your stay?",
      review_rating_label: "Rating",
      review_text_label: "Your review (optional)",
      review_text_placeholder: "Share your experience...",
      review_submit: "Submit review",
      review_success: "Review submitted!",
      review_already_exists: "You've already reviewed this booking.",
      nights: "nights",
      night: "night",
    },
  },
  payments: {
    error: {
      booking_not_pending: "Payment can only be initiated for a pending booking.",
      booking_not_found: "Booking not found.",
      stripe_key_missing: "Stripe is not configured.",
      webhook_invalid_signature: "Invalid webhook signature.",
      double_payout: "One or more bookings are already settled.",
    },
  },
  reviews: {
    error: {
      booking_not_found: "Booking not found.",
      booking_not_confirmed: "Only confirmed bookings can be reviewed.",
      checkout_not_passed: "Reviews can only be submitted after check-out.",
      already_exists: "You have already reviewed this booking.",
    },
  },
  host: {
    listings: {
      title: "My Listings",
      new_listing: "New listing",
      edit: "Edit",
      no_listings: "You have no listings yet.",
      status_draft: "Draft",
      status_published: "Published",
      status_disabled: "Disabled",
      publish: "Publish",
      unpublish: "Unpublish",
      save: "Save changes",
      create_title: "Create a new listing",
      edit_title: "Edit listing",
      field_title: "Title",
      field_description: "Description",
      field_type: "Type",
      field_city: "City",
      field_country: "Country (2-letter code)",
      field_address: "Address",
      field_capacity: "Capacity (guests)",
      field_rate: "Nightly rate",
      field_currency: "Currency",
      field_amenities: "Amenities",
      type_property: "Property",
      type_workspace: "Workspace",
    },
    photos: {
      title: "Photos",
      upload: "Upload photo",
      delete: "Delete",
      uploading: "Uploading...",
      no_photos: "No photos yet.",
    },
    availability: {
      title: "Blocked dates",
      start_label: "Start date",
      end_label: "End date",
      block: "Block dates",
      delete: "Remove",
      no_blocks: "No blocked dates.",
    },
    upcoming: {
      title: "Upcoming bookings",
      no_bookings: "No upcoming bookings.",
      listing_col: "Listing",
      guest_col: "Guest",
      checkin_col: "Check-in",
      checkout_col: "Check-out",
    },
  },
  admin: {
    users: {
      title: "Users",
      email_col: "Email",
      roles_col: "Roles",
      status_col: "Status",
      actions_col: "Actions",
      active: "Active",
      disabled: "Disabled",
      disable: "Disable",
      enable: "Re-enable",
      no_users: "No users found.",
    },
    listings: {
      title: "Listings",
      title_col: "Title",
      type_col: "Type",
      city_col: "City",
      host_col: "Host",
      status_col: "Status",
      actions_col: "Actions",
      disable: "Disable",
      enable: "Re-enable",
      no_listings: "No listings found.",
    },
  },
} as const;

export type Dictionary = typeof en;
