name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main
    paths:
      - "apps/api/**"
      - "packages/**"
      - "pnpm-lock.yaml"

env:
  AWS_REGION: eu-south-2
  ECR_REPOSITORY: nomadhome-repo
  ECS_SERVICE: nomadhome-service
  ECS_CLUSTER: nomadhome-cluster
  ECS_TASK_DEFINITION: nomadhome-task
  CONTAINER_NAME: nomadhome-container

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

      - name: Get ECS Task Public IP
        id: get-ip
        run: |
          TASK_ARN=$(aws ecs list-tasks --cluster nomadhome-cluster --service nomadhome-service --query "taskArns[0]" --output text)

          ENI_ID=$(aws ecs describe-tasks --cluster nomadhome-cluster --tasks $TASK_ARN --query "tasks[0].attachments[0].details[?name=='networkInterfaceId'].value" --output text)

          PUBLIC_IP=$(aws ec2 describe-network-interfaces --network-interface-ids $ENI_ID --query "NetworkInterfaces[0].Association.PublicIp" --output text)

          echo "The new Public IP is: $PUBLIC_IP"
          echo "ip=$PUBLIC_IP" >> $GITHUB_OUTPUT

      - name: Update Vercel Env Var and Redeploy
        run: |
          NEW_URL="http://${{ steps.get-ip.outputs.ip }}:3000"

          curl -X PATCH "https://api.vercel.com/v10/projects/${{ secrets.VERCEL_PROJECT_ID }}/env/VITE_API_URL" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"value\": \"$NEW_URL\", \"target\": [\"production\", \"preview\"]}"

          curl -X POST "https://api.vercel.com/v1/deployments" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"name\": \"nomadhome\", \"project\": \"${{ secrets.VERCEL_PROJECT_ID }}\", \"deploymentDataSource\": \"github\"}"
